version: '3.7'
services:
    myapp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "myapp"
        ports:
            - 5000:5000
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        # environment:
        #   MONGO_INITDB_ROOT_USERNAME: root
        #   MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
          - ./data:/data
        ports:
            - 27017:27017
        command: mongod --dbpath data